[package]
name = "data_check_integrity_lib"
type = "lib"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
utils = { path = "../../utils" }
# noir_native_sha256 = { path = "../../../noir_native_sha256" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
sha512 = { tag = "master", git = "https://github.com/noir-lang/sha512" }
