[package]
name = "compare_age_lib"
type = "lib"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
date = { tag = "v0.5.4", git = "https://github.com/madztheo/noir-date.git" }
utils = { path = "../../utils" }
# noir_native_sha256 = { path = "../../../noir_native_sha256" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
