[package]
name = "sig_check_common"
type = "lib"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
utils = { path = "../../utils" }
sha512 = { tag = "master", git = "https://github.com/zkpassport/sha512" }
# noir_native_sha256 = { path = "../../../noir_native_sha256" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
sha1 = { tag = "v0.11", git = "https://github.com/zac-williamson/sha1" }